server:
  port: 9999
spring:
  thymeleaf:
    cache: false
    mode: HTML
  server:
    datasource:
      url: jdbc:mysql://dev.server:3306/new_fort?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
      username: root
      password: Zhigongzhang1991@
      driverClassName: com.mysql.jdbc.Driver
logging:
  config: classpath:log4j2.xml